apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "habitify.fullname" . }}-frontend
  labels:
    app.kubernetes.io/name: {{ include "habitify.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  config.js: |
    window.__APP_CONFIG = {
      apiBaseUrl: "{{ .Values.frontend.apiBaseUrl }}"
    };
