{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "habitify.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "habitify.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "habitify.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    {{- $cpu := .Values.autoscaling.targetCPUUtilizationPercentage }}
    {{- $mem := .Values.autoscaling.targetMemoryUtilizationPercentage }}
    {{- if or $cpu $mem }}
    {{- if $cpu }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $cpu }}
    {{- end }}
    {{- if $mem }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $mem }}
    {{- end }}
    {{- end }}
{{- end }}
